### ISSUE TITLE
Creating new OSM data

### ISSUE THREAD

**Issue by Amraneze** [kno10/reversegeocode#3]
Hello @kno10,

I'm trying to use your project to compare with [Tile38](https://tile38.com/) to compare which solution is more performant. But I can only run a reverse geocoding on the dataset of OSM 2015. I tried to run the class `ParseOSMLong` but it requires two arguments `inputFile` & `outputFile`. What kind of input file should I give to the function ?

Thank you :)

**Comment by kno10** [comment]
I have not been further using this, and do not remember the details. It was polygon coordinate lists from OSM, but not PBF directly if I recall correctly because the PBF readers would use too much memory.
Please just customize the code to read an input format of your choice.
I will archive this repository.
